server:
  port: 3344
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/garishmzb/springcloud-config.git
          search-paths:
            - springcloud-config
        default-label: main
      label: main
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka