server:
  port: 8001
spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/db2023?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: mzb5201314
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  instance:
    instance-id: payment8001
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 20 #客户端向服务端发送心跳的时间间隔(默认30s)
    lease-expiration-duration-in-seconds: 40 #Eureka服务端最后一次收到心跳等待时间上线，默认(90s)，超时剔除服务
  client:
    register-with-eureka: true #不向服务端注册自己
    fetch-registry: true #自己就是注册中心，不需要检索服务
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002eureka
mybatis:
  type-aliases-package: com.fc.cloud.entity
  mapperLocations: classpath*:mapper/*Mapper.xml